backend/root/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import routers

# import teamaker

# from teamaker.views import TeamMembersViewSet

# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'team_members', TeamMembersViewSet)


from teamaker import urls as teamakerUrls
from teamaker import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.index, name='home' ),
    path('admin/', admin.site.urls, name='admin'),
    path('teamaker/', include(teamakerUrls, namespace='teamaker')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/teamaker/urls.py
from django.urls import path, include
from . import views

app_label = 'teamaker'
app_name = 'teamaker'

urlpatterns = [

    #FORMS

    # path('forms/user', views.userFormSelector, 'new_user'),
    path('forms/team', views.TeamFormView.as_view(), name='team_form'),
    path('forms/member', views.UserFormView.as_view(), name='user_form'),
    
    #These are for editing a single user or team
    path('forms/team/<int:pk>/', views.TeamFormUpdateView.as_view(), name='team_form'),
    path('forms/member/<int:pk>/', views.UserFormUpdateView.as_view(), name='user_form'),

    ##CRUD


    #get, view, put or delete a single member
    path('members/<int:pk>/', views.UserDetails.as_view(), name='members_details'),
     #get all members or create a new one
    path('members/', views.UserList.as_view(),  name='members_list'),

    #get, view, put or delete a single member
    path('teams/<int:pk>/', views.TeamDetails.as_view(), name='teams_details'),
    
    #get all members or create a new one
    path('teams/', views.TeamList.as_view(), name='teams_list'),

]

backend/teamaker/models.py
#abstract base class
from abc import ABC
from django.db import models
from django.db.models.deletion import CASCADE

from django.contrib.auth.models import AbstractUser

#Room for scaling?
class Teams(models.Model):

    team_name = models.CharField(
        verbose_name='Name of the team', 
        blank=False, null=False,
        max_length=200,
        help_text='Provide a name for your team'
    )

    team_description = models.TextField(
        verbose_name='Describe the team', 
        blank=False, null=False,
        help_text='A short blurb about the team'
    )

    def __str__(self):
        return self.team_name

    class Meta:
        pass

class User( AbstractUser ):
    '''
        Team members model    
    '''
    
    class Skill_level(ABC):
        '''
            An abstract class that helps use numberical skill level values in a more readable way.
            The vaiables in this class may be used in queries instead of numberical values
        '''
        JUNIOR = 1
        INTERMEDIATE = 2
        SENIOR = 3    

    #This tuple defines the choices available for the skill level field, which is a numerical value
    skillLevelChoices = (

        (Skill_level.JUNIOR, "Junior"),
        (Skill_level.INTERMEDIATE, "Intermediate"),
        (Skill_level.SENIOR, "Senior"),
    )

    #====== FIELDS ==========================

    USERNAME_FIELD  = 'email'
    EMAIL_FIELD     = 'email'
    REQUIRED_FIELDS =  ['first_name']

    email           = models.EmailField(verbose_name='email address', unique=True)
    username        = models.CharField(max_length=1, help_text='Not used', default='', unique=False, null=True, blank=True)


    skill_level = models.PositiveIntegerField(
        choices=skillLevelChoices, 
        default=Skill_level.JUNIOR
    )

    #Room for scaling?
    # team = models.ForeignKey(
    #     Teams,
    #     verbose_name="Name of team",
    #     help_text="Which team does this member belong to?",
    #     blank=False, 
    #     null=False,
    #     on_delete=CASCADE
    # )

    #===== END OF FIELDS ====================

    def __str__(self):
        return __class__.__name__

    class Meta:
        app_label = 'teamaker'
        ordering = []
        verbose_name        = "Team member"
        verbose_name_plural = "Team members"

backend/teamaker/views.py
from django.http import Http404, request
from django.urls import reverse

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from django.views.generic import edit

from rest_framework import serializers, status, generics
from rest_framework.views import APIView
from rest_framework.response import Response

from . import models
from . import models_forms

from django.core.exceptions import ObjectDoesNotExist


class TeamSerializer(serializers.ModelSerializer):
    '''
        Simple model serializer to serialize data from team
    '''
    
    class Meta:
        model = models.Teams
        fields = '__all__'

class TeamMembersSerializer(serializers.ModelSerializer):
    '''
        Simple model serializer to serialize data from User model
    '''
    
    class Meta:
        model = models.User
        # fields = ['pk', 'first_name', 'last_name', 'email', 'skill_level', 'team']
        fields = ['pk', 'first_name', 'last_name', 'email', 'skill_level']

# # ViewSets define the view behavior.
# class TeamMembersViewSet(viewsets.ModelViewSet):
    
#     queryset = models.User.objects.all()
#     serializer_class = TeamMembersSerializer

class UserDetails(APIView):
    """
        Retrieve, update or delete a single team member.
    """

    authentication_classes = [] #disables authentication
    permission_classes = [] #disables permission

    def get_queryset(self, pk):
        try:
            return models.User.objects.get(pk=pk)
        except models.User.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        
        queryset = self.get_queryset(pk)
        serializer = TeamMembersSerializer(queryset)
        return Response(serializer.data)

    def put(self, request, pk, format=None):

        queryset = self.get_queryset(pk)
        serializer = TeamMembersSerializer(queryset, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        
        queryset = self.get_queryset(pk)
        queryset.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class UserList(generics.ListCreateAPIView):
    '''
        The base class is a mixed in version of APIView that allows us the GET and POST methods 
    '''

    authentication_classes = [] #disables authentication
    permission_classes = [] #disables permission

    queryset = models.User.objects.all()
    serializer_class = TeamMembersSerializer 
 

class TeamDetails(APIView):
    """
        Retrieve, update or delete a single team member.
    """

    authentication_classes = [] #disables authentication
    permission_classes = [] #disables permission

    def get_queryset(self, pk):
        try:
            return models.Teams.objects.get(pk=pk)
        except models.Teams.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        
        queryset = self.get_queryset(pk)
        serializer = TeamSerializer(queryset)
        return Response(serializer.data)

    def put(self, request, pk, format=None):

        queryset = self.get_queryset(pk)
        serializer = TeamSerializer(queryset, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        
        queryset = self.get_queryset(pk)
        queryset.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class TeamList(generics.ListCreateAPIView):

    authentication_classes = [] #disables authentication
    permission_classes = [] #disables permission

    queryset = models.Teams.objects.all()
    serializer_class = TeamSerializer 


class TeamFormView(edit.FormView):
    form_class = models_forms.TeamsForm   
    template_name = 'teamaker/forms/teams.html'
    success_url = '#'

class TeamFormUpdateView(edit.UpdateView):
    form_class = TeamFormView.form_class  
    template_name = TeamFormView.template_name
    success_url = TeamFormView.success_url
    model=models.Teams

class UserFormView(edit.FormView):
    form_class = models_forms.UserForm   
    template_name = 'teamaker/forms/members.html'
    success_url = '#'

class UserFormUpdateView(edit.UpdateView):
    form_class = UserFormView.form_class  
    template_name = UserFormView.template_name
    success_url = UserFormView.success_url
    model=models.User

def index(request):
    return render(request, 'index.html')

backend/templates/base.html
{% load static %}
<html>
    <head>
        <title>Tea maker application - v 0.1</title> 

        <link rel="stylesheet" src="{% static '/css/index.css' %}"  >        
        <link rel="shortcut icon" type="image/jpg" href="{% static 'favicon.ico' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        
    </head>
    <body>
        {% block body %}
        <main>
            <div id="main_container"></div>
        </main>
        {% endblock %}
    </body>
</html>

backend/templates/index.html
{% extends "./base.html" %}
{% load static %}

{% block body %}

<main><div id="main_container" class="container p-2"></div></main>
<script src="{% static 'js/index.js' %}"></script>

{% endblock %}

backend/templates/teamaker/forms/members.html
{% load bootstrap4 %}
<form action="{% url 'teamaker:members_list' %}?format=json" >
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}<button type="submit" class="btn btn-primary">Submit</button>{% endbuttons %}
</form>

backend/templates/teamaker/forms/teams.html
{% load bootstrap4 %}
<form action="{% url 'teamaker:teams_list' %}?format=json" >
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons %}<button type="submit" class="btn btn-primary">Add team</button>{% endbuttons %}

</form>

templates/index.html
{% extends "./base.html" %}
{% load static %}

{% block body %}

<main>
    <div id="main_container"></div>
</main>

<script src="{% static '/js/index.js' %}"></script>

{% endblock %}

templates/teamaker/forms/user.html
{% extends "../../base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block body %}

<div class="container my-3">

    <h2>New member form</h2>

    <form class="inputForms" >

        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}

    </form>

</div>

<script src="{% static '/teamaker/index.js' %}"></script>
{% endblock %}